all :
	g++ -g "Starting window.cpp" ClassesAndHeaders/Laivas.cpp ClassesAndHeaders/Shot.cpp ClassesAndHeaders/dbconnector.cpp "Starting window.h" -o frontend -Lusr/lib -lsfml-graphics -lsfml-system -lsfml-window -lmysqlclient
