all :
	g++ -g "Starting window.cpp" ClassesAndHeaders/Laivas.cpp ClassesAndHeaders/Shot.cpp ClassesAndHeaders/dbconnector.cpp "Starting window.h" stdcomm-linux.cpp -o frontend -I/usr/include/mysql -lsfml-graphics -lsfml-system -lsfml-window -lmysqlclient
