drop database battleships;

-- MySQL Script generated by MySQL Workbench
-- Fri Nov  8 08:20:08 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema battleships
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema battleships
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `battleships` DEFAULT CHARACTER SET utf8 ;
USE `battleships` ;
SET GLOBAL auto_increment_increment=1;
-- -----------------------------------------------------
-- Table `battleships`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `battleships`.`users` (
  `userID` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `wins` INT NOT NULL DEFAULT 0,
  `losses` INT NOT NULL DEFAULT 0,
  `is_ai` TINYINT(1) NOT NULL DEFAULT 0,
  `current_lobbyID` INT NULL,
  PRIMARY KEY (`userID`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `battleships`.`lobbies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `battleships`.`lobbies` (
  `lobbyID` INT NOT NULL AUTO_INCREMENT,
  `lobby_name` VARCHAR(45) NOT NULL DEFAULT 'unnamed lobby',
  `lobby_status` CHAR(1) NOT NULL DEFAULT 'w',
  `adminID` INT NOT NULL,
  `opponentID` INT NULL,
  `user_input` VARCHAR(5) NOT NULL DEFAULT '',
  `console_output` VARCHAR(5) NOT NULL DEFAULT '',
  `admin_map` VARCHAR(100) NOT NULL DEFAULT '',
  `opponent_map` VARCHAR(100) NOT NULL DEFAULT '',
  `historyID` INT NULL COMMENT 'INSERT INTO history(game_name, player1_ID, player2_ID, map1, map2) SELECT lobbies.lobby_name, lobbies.adminID, lobbies.opponentID,\'101011\',\'015120\' FROM lobbies WHERE lobbies.lobbyID=1',
  `game_status` VARCHAR(1) NOT NULL DEFAULT 'n',
  `current_player` INT NOT NULL DEFAULT -1,
  PRIMARY KEY (`lobbyID`),
  INDEX `admin_idx` (`adminID` ASC) VISIBLE,
  INDEX `user_idx` (`opponentID` ASC) VISIBLE,
  CONSTRAINT `adminID`
    FOREIGN KEY (`adminID`)
    REFERENCES `battleships`.`users` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `opponentID`
    FOREIGN KEY (`opponentID`)
    REFERENCES `battleships`.`users` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `battleships`.`history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `battleships`.`history` (
  `gameID` INT NOT NULL AUTO_INCREMENT,
  `game_name` VARCHAR(45) NOT NULL,
  `player1_ID` INT NOT NULL,
  `player2_ID` INT NOT NULL,
  `map1` VARCHAR(100) NOT NULL,
  `map2` VARCHAR(100) NOT NULL,
  `winnerID` INT NOT NULL DEFAULT -1,
  PRIMARY KEY (`gameID`),
  INDEX `player1_id_idx` (`player1_ID` ASC) VISIBLE,
  INDEX `player2_id_idx` (`player2_ID` ASC) VISIBLE,
  CONSTRAINT `player1_ID`
    FOREIGN KEY (`player1_ID`)
    REFERENCES `battleships`.`users` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `player2_ID`
    FOREIGN KEY (`player2_ID`)
    REFERENCES `battleships`.`users` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `battleships`.`moves`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `battleships`.`moves` (
  `gameID` INT NOT NULL,
  `moveID` INT NOT NULL,
  `move_pos` VARCHAR(5) NOT NULL,
  `move_res` VARCHAR(5) NOT NULL,
  `playerID` INT NOT NULL,
  PRIMARY KEY (`gameID`, `moveID`),
  INDEX `playerID_idx` (`playerID` ASC) VISIBLE,
  CONSTRAINT `gameID`
    FOREIGN KEY (`gameID`)
    REFERENCES `battleships`.`history` (`gameID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `playerID`
    FOREIGN KEY (`playerID`)
    REFERENCES `battleships`.`users` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE USER 'ServerAdmin' IDENTIFIED BY 'admin';

GRANT ALL ON `battleships`.* TO 'ServerAdmin';
CREATE USER 'ActiveUser' IDENTIFIED BY 'admin';

GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `battleships`.* TO 'ActiveUser';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO users(username,is_ai) VALUES('ai_random',1);
INSERT INTO users(username,is_ai) VALUES('ai_random2',1);
INSERT INTO lobbies(lobby_name,adminID) VALUES('AI_lobby',1);
UPDATE lobbies SET opponentID=2, lobby_status='r' WHERE lobbyID=1;
